name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build ./src/Solution.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./src/Solution.sln --configuration Release
